// Generated by CoffeeScript 1.6.2
/*
rsmq

A Really Simple Message Queue based on Redis

The MIT License (MIT)

Copyright © 2013 Patrick Liess, http://www.tcs.de

Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the “Software”), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
*/


(function() {
  var RedisInst, RedisSMQ, crypto, _,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  crypto = require("crypto");

  _ = require("underscore");

  RedisInst = require("redis");

  RedisSMQ = (function() {
    function RedisSMQ(redisport, redishost, redisns) {
      if (redisport == null) {
        redisport = 6379;
      }
      if (redishost == null) {
        redishost = "127.0.0.1";
      }
      this.redisns = redisns != null ? redisns : "rsmq";
      this.sendMessage = __bind(this.sendMessage, this);
      this.receiveMessage = __bind(this.receiveMessage, this);
      this.deleteQueue = __bind(this.deleteQueue, this);
      this.deleteMessage = __bind(this.deleteMessage, this);
      this.createQueue = __bind(this.createQueue, this);
      this.changeMessageVisibility = __bind(this.changeMessageVisibility, this);
      this._getQueue = __bind(this._getQueue, this);
      this.redisns = this.redisns + ":";
      this.redis = RedisInst.createClient(redisport, redishost);
      this.initScript();
    }

    RedisSMQ.prototype._getQueue = function(qname, uid, cb) {
      var mc,
        _this = this;

      mc = [["hmget", "" + this.redisns + qname + ":Q", "vt", "delay", "maxsize"], ["time"]];
      this.redis.multi(mc).exec(function(err, resp) {
        var ms, q, ts;

        if (err) {
          cb(err);
          return;
        }
        if (resp[0][0] === null || resp[0][1] === null || resp[0][2] === null) {
          cb("Queue not found");
          return;
        }
        ms = _this._formatZeroPad(Number(resp[1][1]), 6);
        ts = Number(resp[1][0] + ms.toString(10).slice(0, 3));
        q = {
          vt: parseInt(resp[0][0], 10),
          delay: parseInt(resp[0][1], 10),
          maxsize: parseInt(resp[0][2], 10),
          ts: ts
        };
        if (uid) {
          uid = qname + Math.random();
          uid = crypto.createHash('md5').update(uid).digest("hex");
          q.uid = Number(resp[1][0] + ms).toString(36) + uid;
        }
        cb(null, q);
      });
    };

    RedisSMQ.prototype.changeMessageVisibility = function(options, cb) {
      var _this = this;

      if (this._validate(options, ["qname", "id", "vt"], cb) === false) {
        return;
      }
      this._getQueue(options.qname, false, function(err, q) {
        if (err) {
          cb(err);
          return;
        }
        return _this.redis.evalsha(_this.changeMessageVisibility_sha1, 3, "" + _this.redisns + options.qname, options.id, q.ts + options.vt * 1000, function(err, resp) {
          if (err) {
            cb(err);
            return;
          }
          cb(null, resp);
        });
      });
    };

    RedisSMQ.prototype.createQueue = function(options, cb) {
      var mc, _ref, _ref1, _ref2,
        _this = this;

      options.vt = (_ref = options.vt) != null ? _ref : 30;
      options.delay = (_ref1 = options.delay) != null ? _ref1 : 0;
      options.maxsize = (_ref2 = options.maxsize) != null ? _ref2 : 65536;
      if (this._validate(options, ["qname", "vt", "delay", "maxsize"], cb) === false) {
        return;
      }
      mc = [["hsetnx", "" + this.redisns + options.qname + ":Q", "vt", options.vt], ["hsetnx", "" + this.redisns + options.qname + ":Q", "delay", options.delay], ["hsetnx", "" + this.redisns + options.qname + ":Q", "maxsize", options.maxsize]];
      this.redis.multi(mc).exec(function(err, resp) {
        if (err) {
          cb(err);
          return;
        }
        if (resp[0] === 0) {
          cb("Queue exists");
          return;
        }
        _this.redis.sadd("" + _this.redisns + "QUEUES", options.qname, function(err, resp) {
          if (err) {
            cb(err);
            return;
          }
          cb(null, 1);
        });
      });
    };

    RedisSMQ.prototype.deleteMessage = function(options, cb) {
      var key, mc;

      if (this._validate(options, ["qname", "id"], cb) === false) {
        return;
      }
      key = "" + this.redisns + options.qname;
      mc = [["zrem", key, options.id], ["hdel", "" + key + ":Q", "" + options.id, "" + options.id + ":rc", "" + options.id + ":fr"]];
      this.redis.multi(mc).exec(function(err, resp) {
        if (err) {
          cb(err);
          return;
        }
        if (resp[0] === 1 && resp[1] > 0) {
          cb(null, 1);
        } else {
          cb(null, 0);
        }
      });
    };

    RedisSMQ.prototype.deleteQueue = function(options, cb) {
      var key, mc;

      if (this._validate(options, ["qname"], cb) === false) {
        return;
      }
      key = "" + this.redisns + options.qname;
      mc = [["del", "" + key + ":Q"], ["del", key], ["srem", "" + this.redisns + "QUEUES", options.qname]];
      this.redis.multi(mc).exec(function(err, resp) {
        if (err) {
          cb(err);
          return;
        }
        if (resp[0] === 0) {
          cb("Queue not found");
          return;
        }
        cb(null, 1);
      });
    };

    RedisSMQ.prototype.initScript = function(cb) {
      var script_changeMessageVisibility, script_receiveMessage,
        _this = this;

      script_receiveMessage = 'local msg = redis.call("ZRANGEBYSCORE", KEYS[1], "-inf", KEYS[2], "LIMIT", "0", "1")\
			if #msg == 0 then\
				return {}\
			end\
			redis.call("ZADD", KEYS[1], KEYS[3], msg[1])\
			redis.call("HINCRBY", KEYS[1] .. ":Q", "totalrecv", 1)\
			local mbody = redis.call("HGET", KEYS[1] .. ":Q", msg[1])\
			local rc = redis.call("HINCRBY", KEYS[1] .. ":Q", msg[1] .. ":rc", 1)\
			local o = {msg[1], mbody, rc}\
			if rc==1 then\
				redis.call("HSET", KEYS[1] .. ":Q", msg[1] .. ":fr", KEYS[2])\
				table.insert(o, KEYS[2])\
			else			\
				local fr = redis.call("HGET", KEYS[1] .. ":Q", msg[1] .. ":fr")\
				table.insert(o, fr)\
			end\
			return o';
      script_changeMessageVisibility = 'local msg = redis.call("ZSCORE", KEYS[1], KEYS[2])\
			if not msg then\
				return 0\
			end\
			redis.call("ZADD", KEYS[1], KEYS[3], KEYS[2])\
			return 1';
      this.redis.script("load", script_receiveMessage, function(err, resp) {
        _this.receiveMessage_sha1 = resp;
      });
      this.redis.script("load", script_changeMessageVisibility, function(err, resp) {
        _this.changeMessageVisibility_sha1 = resp;
      });
    };

    RedisSMQ.prototype.receiveMessage = function(options, cb) {
      var _this = this;

      if (!this.receiveMessage_sha1) {
        return {};
      }
      if (this._validate(options, ["qname"], cb) === false) {
        return;
      }
      this._getQueue(options.qname, false, function(err, q) {
        var _ref;

        if (err) {
          cb(err);
          return;
        }
        options.vt = (_ref = options.vt) != null ? _ref : q.vt;
        if (_this._validate(options, ["vt"], cb) === false) {
          return;
        }
        _this.redis.evalsha(_this.receiveMessage_sha1, 3, "" + _this.redisns + options.qname, q.ts, q.ts + options.vt * 1000, function(err, resp) {
          var o;

          if (err) {
            cb(err);
            return;
          }
          if (!resp.length) {
            cb(null, {});
            return;
          }
          o = {
            id: resp[0],
            message: resp[1],
            rc: resp[2],
            fr: Number(resp[3]),
            sent: parseInt(parseInt(resp[0].slice(0, 10), 36) / 1000)
          };
          cb(null, o);
        });
      });
    };

    RedisSMQ.prototype.sendMessage = function(options, cb) {
      var _this = this;

      if (this._validate(options, ["qname"], cb) === false) {
        return;
      }
      this._getQueue(options.qname, true, function(err, q) {
        var mc, _ref;

        if (err) {
          cb(err);
          return;
        }
        options.delay = (_ref = options.delay) != null ? _ref : q.delay;
        if (_this._validate(options, ["delay"], cb) === false) {
          return;
        }
        if (typeof options.message !== "string") {
          cb("Message must be a string");
          return;
        }
        if (options.message.length > q.maxsize) {
          cb("Message too long");
          return;
        }
        mc = [["zadd", "" + _this.redisns + options.qname, q.ts + options.delay * 1000, q.uid], ["hset", "" + _this.redisns + options.qname + ":Q", q.uid, options.message], ["hincrby", "" + _this.redisns + options.qname + ":Q", "totalsent", 1]];
        _this.redis.multi(mc).exec(function(err, resp) {
          if (err) {
            cb(err);
            return;
          }
          cb(null, q.uid);
        });
      });
    };

    RedisSMQ.prototype._formatZeroPad = function(num, count) {
      return ((Math.pow(10, count) + num) + "").substr(1);
    };

    RedisSMQ.prototype._VALID = {
      qname: /^([a-zA-Z0-9_-]){1,80}$/,
      id: /^([a-zA-Z0-9:]){42}$/
    };

    RedisSMQ.prototype._validate = function(o, items, cb) {
      var item, _i, _len;

      for (_i = 0, _len = items.length; _i < _len; _i++) {
        item = items[_i];
        switch (item) {
          case "qname":
          case "id":
            if (!o[item]) {
              cb("No " + item + " supplied");
              return false;
            }
            o[item] = o[item].toString();
            if (!this._VALID[item].test(o[item])) {
              cb("Invalid " + item + " format");
              return false;
            }
            break;
          case "vt":
          case "delay":
            o[item] = parseInt(o[item], 10);
            if (_.isNaN(o[item]) || !_.isNumber(o[item]) || o[item] < 0 || o[item] > 86400) {
              cb("" + item + " must be between 0 and 86400");
              return false;
            }
            break;
          case "maxsize":
            o[item] = parseInt(o[item], 10);
            if (_.isNaN(o[item]) || !_.isNumber(o[item]) || o[item] < 1024 || o[item] > 65536) {
              cb("" + item + " must be between 1024 and 65536");
              return false;
            }
        }
      }
      return o;
    };

    return RedisSMQ;

  })();

  module.exports = RedisSMQ;

}).call(this);
